from __future__ import annotations

def default_three_template() -> str:
    src = "__GTKV_THREE_SRC__"
    return (
        "<!doctype html>\n"
        "<html>\n"
        "  <head>\n"
        "    <meta charset=\"utf-8\" />\n"
        "    <style>body { margin: 0; background: #111; color: #ddd; font-family: monospace; }</style>\n"
        "  </head>\n"
        "  <body>\n"
        "    <script type=\"module\">\n"
        "      const error = (msg) => {\n"
        "        const el = document.createElement('pre');\n"
        "        el.textContent = msg;\n"
        "        el.style.whiteSpace = 'pre-wrap';\n"
        "        el.style.padding = '12px';\n"
        "        document.body.appendChild(el);\n"
        "      };\n"
        f"      const src = \"{src}\";\n"
        "      import(src).then((THREE) => {\n"
        "        const scene = new THREE.Scene();\n"
        "        const camera = new THREE.PerspectiveCamera(60, innerWidth/innerHeight, 0.1, 1000);\n"
        "        const renderer = new THREE.WebGLRenderer({ antialias: true });\n"
        "        renderer.setPixelRatio(devicePixelRatio || 1);\n"
        "        renderer.setSize(innerWidth, innerHeight);\n"
        "        document.body.appendChild(renderer.domElement);\n"
        "        const geometry = new THREE.BoxGeometry(1, 1, 1);\n"
        "        const material = new THREE.MeshStandardMaterial({ color: 0xaaaaaa, metalness: 0.3, roughness: 0.4 });\n"
        "        const cube = new THREE.Mesh(geometry, material);\n"
        "        scene.add(cube);\n"
        "        const light = new THREE.DirectionalLight(0xffffff, 1);\n"
        "        light.position.set(2, 3, 4);\n"
        "        scene.add(light);\n"
        "        camera.position.z = 3;\n"
        "        function animate() {\n"
        "          requestAnimationFrame(animate);\n"
        "          cube.rotation.x += 0.01;\n"
        "          cube.rotation.y += 0.015;\n"
        "          renderer.render(scene, camera);\n"
        "        }\n"
        "        animate();\n"
        "        window.addEventListener('resize', () => {\n"
        "          camera.aspect = innerWidth/innerHeight;\n"
        "          camera.updateProjectionMatrix();\n"
        "          renderer.setSize(innerWidth, innerHeight);\n"
        "        });\n"
        "      }).catch((err) => {\n"
        "        error(String(err));\n"
        "      });\n"
        "    </script>\n"
        "  </body>\n"
        "</html>\n"
    )
